image: alpine:latest

stages:
  - teste

verificar-arquivos:
  stage: teste
  script:
    - echo "Verificando se index.html existe..."
    - test -f index.html || (echo "index.html não encontrado!" && exit 1)

    - echo "Verificando se index.html não está vazio..."
    - test -s index.html || (echo "index.html está vazio!" && exit 1)

    - echo "Verificando se style.css existe..."
    - test -f src/css/style.css || (echo "style.css não encontrado!" && exit 1)

    - echo "Procurando tag <html>..."
    - grep -q "<html" index.html || (echo "Tag <html> não encontrada!" && exit 1)

    - echo "Validação concluída com sucesso!"