image: alpine:latest

stages:
  - teste

verificar-arquivos:
  stage: teste
  script:
    - echo "Verificando se src/index.html existe..."
    - test -f src/index.html || (echo "index.html não encontrado!" && exit 1)

    - echo "Verificando se não está vazio..."
    - test -s src/index.html || (echo "index.html está vazio!" && exit 1)

    - echo "Procurando tag <html>..."
    - grep -q "<html" src/index.html || (echo "Tag <html> não encontrada!" && exit 1)

    - echo "Validação concluída com sucesso!"